version: '3.7'
services:
  weaviate:
    image: semitechnologies/weaviate:1.22.3
    container_name: weaviate
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - ENABLE_MODULES=text2vec-openai
      - OPENAI_APIKEY=DUMMY_KEY
